### ISSUE TITLE
can you add lilu + plugin list as one?

### ISSUE THREAD

**Issue by Sher1ocks** [corpnewt/Lilu-and-Friends#11]
i have been used your script.
first of all, thanks.
now, there is list that lilu and plugin and other kexts.
if i want to build lilu + plugins once, i have to type number one by one.
can you improve this part?
example. if type 'L', will check lilu+plugins.

or divide list again like this
lilu
plugins
other kexts

because user confuse kext if user doesn't have many info.

sorry my bad english.

**Comment by Sher1ocks** [comment]
![2018-06-10 7 00 10](https://user-images.githubusercontent.com/2107738/41200502-8f0cd610-6ce0-11e8-8491-17cd1c3de5fc.png)
also script has color issue in 10.14 when using dark mode

**Comment by corpnewt** [comment]
You can actually use the Color Picker (`C` in the main menu) to change the colors to work better.  Also - there's a Profiles menu that allows you to save the current selection to a profile which can be loaded later.

The main menu with the Highlight Color set to White bold:

![image](https://user-images.githubusercontent.com/12772521/41206104-6bba5924-6cc4-11e8-9592-b8802f4375b5.png)

And the profiles menu setup with a default profile:

![image](https://user-images.githubusercontent.com/12772521/41206121-d30f3d88-6cc4-11e8-9c50-b09e847cba98.png)

It should be pretty easy to setup a Lilu, Plugins, and Other profile that build the respective kexts.  Also, if you need to select/deselect a number of kexts at once in the main menu, you can type them all at once separated by a non-alphanumeric character (such as a space, comma, etc).  For example, `1, 2, 3, 4` would toggle the first 4 kexts - any that were selected would be deselected, and any that weren't would be selected.

Hopefully that answers your questions - if I missed anything, or could explain things better please let me know!

**Comment by corpnewt** [comment]
I [just addressed](https://github.com/corpnewt/Lilu-and-Friends/commit/8ca303073701c0db9e96be7140329ae9bb7df99b) an issue with the colors being reset after updates - that shouldn't happen anymore.

**Comment by Sher1ocks** [comment]
thank you.
you need to check [https://github.com/acidanthera/Lilu/blob/master/KnownPlugins.md](url) again
IntelGraphicsDVMTFixup
https://github.com/acidanthera/BT4LEContiunityFixup

**Comment by corpnewt** [comment]
Should be updated now. 

DVMTFixup is now migrated to WEG in any profiles (as well as removed from the plugin selection), and BT4LECFU's repo is updated.

I'll need to update the readme to reflect the changes when I'm home this evening though.

Thanks!

**Comment by Sher1ocks** [comment]
thank you!!😊
