### ISSUE TITLE
Updater instance has no attribute 'rt_color'`

### ISSUE THREAD

**Issue by xyx208** [corpnewt/Lilu-and-Friends#17]
Brother, you did a great job! But what is the cause of this mistake? My programming ability is not good, please forgive me!
`  #######################################################Traceback (most recent call last):  File "/Volumes/Doc/Lilu-and-Friends-master/Scripts/updater.py", line 1416, in <module>
    up = Updater()
  File "/Volumes/Doc/Lilu-and-Friends-master/Scripts/updater.py", line 78, in __init__
    self.head("Xcode First Launch")
  File "/Volumes/Doc/Lilu-and-Friends-master/Scripts/updater.py", line 360, in head
    middle = middle.replace(len_text, text + self.rt_color) # always reset just in case
AttributeError: Updater instance has no attribute 'rt_color'`

OS:MACOS 10.13.6
XCODE: 9.4.1

I tried to reinstall Xcode.

thanks for all your work!

**Comment by corpnewt** [comment]
Hey @xyx208 - it looks like I was trying to access some colors prior to setting them up; so not something you've done at all.  I just pushed a commit to the updater.py file - would you mind testing that out?  If it works, I'll push the "official" update.  Thanks!

**Comment by xyx208** [comment]
now,the message is 
`
  #######################################################
 #                Xcode First Launch                   #
#######################################################
 
Password:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
 
If everything ran correctly please relaunch the script.`

thanks for your work!

**Comment by xyx208** [comment]
i used this command,it seems work now!
` sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/`

thanks again for your works!!!
