### ISSUE TITLE
Excuse me，can we add AppleSupportPKG and AptioFixPKG into Lilu-and-Friends please?

### ISSUE THREAD

**Issue by whoisme007** [corpnewt/Lilu-and-Friends#19]
I found it's very comfortable to open Lilu-and-friends every time I open the PC,It makes me feel good to be everythings newest.
but I have to waste a lot of time to download AppleSupportPKG and AptioFixPKG,download UDK,and makebuild it.
can we add AppleSupportPKG and AptioFixPKG into Lilu-and-Friends please?
thank you so much.

**Comment by corpnewt** [comment]
They're buildable via my CloverExtractor script - you can find that [here](https://github.com/corpnewt/CloverExtractor).
