### ISSUE TITLE
Cannot build VoodooHDA.

### ISSUE THREAD

**Issue by whoisme007** [corpnewt/Lilu-and-Friends#21]
Building VoodooHDA (1 of 1)
    Downloading VoodooHDA...
^CCommand not found!
Cleaning up...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

Building VoodooHDA (1 of 1)
    Downloading VoodooHDA...

Succeeded:

    None

Failed:

    VoodooHDA
 
Build took 5 minutes, 23 seconds.

__________

Succeeded:

    CPUFriend v1.1.5
    CodecCommander v2.7.1
    EnableLidWake v4.0.2
    HibernationFixup v1.2.3
    Lilu v1.2.7
    LiluFriend v1.1.0
    NoTouchID v1.0.1
    RealtekRTL8100 v2.0.1
    RealtekRTL8111 v2.2.2
    USBInjectAll v0.6.8
    VoodooPS2Controller v1.9.2
    WhateverGreen v1.2.4

Failed:

    None
 
Build took 1 minute, 10 seconds.

Press [enter] to return to the main menu...

**Comment by corpnewt** [comment]
Looks like it's just SourceForge being slow as it doesn't fully download VoodooHDA - and you ctrl+C'ed your way out of the script.  For whatever reason, SourceForge repos are cloned suuuuper slow.  I've noticed this with the FakeSMC (HWSensors3) repo as well.  Keep an eye on your network, and ensure there's still traffic, but it *should* finish eventually.
