### ISSUE TITLE
Non-interactive mode?

### ISSUE THREAD

**Issue by kibiz0r** [corpnewt/Lilu-and-Friends#22]
I'm trying to get my whole hackintosh setup down to a single script, and I think this build process is the last holdout. Any chance of invoking this non-interactively?

**Comment by corpnewt** [comment]
There isn't anything currently setup, but I could look into adding cli args.

**Comment by corpnewt** [comment]
Just added cli args - please test and let me know if they work well for you, or if you find any bugs.

**Comment by kibiz0r** [comment]
Beautiful! Thank you!
