### ISSUE TITLE
DiskArbitrationFixupFailed

### ISSUE THREAD

**Issue by whoisme007** [corpnewt/Lilu-and-Friends#23]
Building Lilu:
    Downloading Lilu...
Building DiskArbitrationFixup (1 of 1)
    Downloading DiskArbitrationFixup...
Command not found!
Cleaning up...

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

Succeeded:

    None

Failed:

    DiskArbitrationFixup

**Comment by corpnewt** [comment]
The `Command not found!` error likely implies that `git` or `xcodebuild` do not exist.  Do any of the other kexts build on your current setup?

I just built it on 10.14.4 beta 1 (18E174f) successfully:
```
  #######################################################
 #                  Building 1 kext                    #
#######################################################
 
Building Lilu:
    Downloading Lilu...
    Building debug version...
Building DiskArbitrationFixup (1 of 1)
    Downloading DiskArbitrationFixup...
    Building release version...
    SDK Override "BUILD_DIR=/private/var/folders/z0/d08l5k152y1f5kjz_2jdgjn40000gn/T/tmp62ta1jas/Lilu/DiskArbitrationFixup/build/ -sdk macosx10.11"...
Zipping...
Built DiskArbitrationFixup v1.0.0
Cleaning up...
```
```
  #######################################################
 #                  1 of 1 Succeeded                   #
#######################################################
 
Succeeded:

    DiskArbitrationFixup v1.0.0

Failed:

    None
 
Build took 5 seconds.
```
Might make sure your dev environment is setup correctly?

-CorpNewt

**Comment by whoisme007** [comment]
now it's ok.
suggest it's the network problem of ChinaGreatWall, 'cos i just update the chinaDNS then it's ok...

Succeeded:

    AppleALC v1.3.5
    DiskArbitrationFixup v1.0.0
    Lilu v1.3.2
    VoodooPS2Controller v1.9.2
    WhateverGreen v1.2.7

Failed:

    None
 
Build took 1 minute, 39 seconds.

**Comment by corpnewt** [comment]
Glad that it seems to work alright now!
