### ISSUE TITLE
Add support for the new NVMeFix.

### ISSUE THREAD

**Issue by ReddestDream** [corpnewt/Lilu-and-Friends#26]
NVMeFix is a new acidanthera kext that utilizes Lilu. Fixes up NVMe issues on hack and Mac. Looks worth supporting. Thx! :)

https://github.com/acidanthera/NVMeFix

If I get time I might write in some new code to support it and do a pull request. But I might not have time today. :/

**Comment by johnnynunez** [comment]
@ReddestDream https://github.com/corpnewt/Lilu-and-Friends/pull/27

**Comment by corpnewt** [comment]
Merged per @johnnync13's PR in [this commit](https://github.com/corpnewt/Lilu-and-Friends/commit/7cbe3d19c3b21c738d555312fa65f0fdb5e9709a).

-CorpNewt
