### ISSUE TITLE
VirtualSMC no longer builds VirtualSMC.efi.

### ISSUE THREAD

**Issue by ReddestDream** [corpnewt/Lilu-and-Friends#29]
VirtualSMC no longer builds VirtualSMC.efi since its functionality has been integrated into OC.

https://github.com/acidanthera/VirtualSMC/commit/9b99516dc34094b8ee73f8ee4ae774688bf54529

Lilu-and-friends now fails to build since the driver is not present. Thanks!

**Comment by corpnewt** [comment]
Should be fixed in [this commit](https://github.com/corpnewt/Lilu-and-Friends/commit/5eec866fb95a149c22a083ea9f3b97788e199b72).

-CorpNewt
