### ISSUE TITLE
Some issues with several options

### ISSUE THREAD

**Issue by Matgen84** [corpnewt/Lilu-and-Friends#3]
Hi

Very good job, thanks.

But when I try to compile for example GenericXHCIUSB or ATH9KFixup, no succeed.

Please help

**Comment by corpnewt** [comment]
Hey Matgen84,

ATH9KFixup isn't compatible with Lilu 1.2.0+ (last I looked at least).  And GenericUSBXHCI wouldn't build with an SDK newer than 10.10 for me - so to get that working, you'll need to grab the 10.10 sdk from [here](https://github.com/phracker/MacOSX-SDKs), then copy it to */Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs*.  The *plugins.json* already targets the macosx10.10 sdk via the [Build Opts](https://github.com/corpnewt/Lilu-and-Friends/blob/master/Scripts/plugins.json#L167-L171), so you shouldn't need to do anything more than install the SDK.

Hopefully that helps!

-CorpNewt
