### ISSUE TITLE
Can't build corrrectly

### ISSUE THREAD

**Issue by johnnynunez** [corpnewt/Lilu-and-Friends#31]
<img width="373" alt="Screenshot 2020-01-27 at 12 28 23" src="https://user-images.githubusercontent.com/22727137/73171271-aad34780-4100-11ea-881c-b4eaf31bfa61.png">

VoodooPS2: https://github.com/acidanthera/VoodooPS2
Voodooi2c: https://github.com/alexandred/VoodooI2C

An add VoodooInput: https://github.com/acidanthera/VoodooInput

**Comment by Mateo1234454545** [comment]
Same here.

**Comment by johnnynunez** [comment]
with voodooi2c is the same
