### ISSUE TITLE
Kext names are blank

### ISSUE THREAD

**Issue by bandithedoge** [corpnewt/Lilu-and-Friends#35]
![Screen Shot 2021-01-05 at 18 25 18](https://user-images.githubusercontent.com/26331682/103678086-67759000-4f83-11eb-9a18-6ec3aa6daa86.png)

This happens both in iTerm and Kitty.

**Comment by Lacedaemon** [comment]
Try changing the 'Highlight' color in Main Menu > Color Picker.
