### ISSUE TITLE
New RTL8111 driver by Mieze

### ISSUE THREAD

**Issue by DMNerd** [corpnewt/Lilu-and-Friends#36]
Hello. I was wondering if it would be possible to add the new RTL driver Mieze is working on?

the source: https://github.com/Mieze/RTL8111_driver_for_OS_X

Right now she is buidling the test versions and providing it to insanelymac herself. It would be cool if anyone could compile on their own with your wonderfull tool :)

Thank you very much.

**Comment by corpnewt** [comment]
Looks like she pushed the code to the main repo - so this script will build it as-is.

-CorpNewt
