### ISSUE TITLE
Issues compiling voodooi2c

### ISSUE THREAD

**Issue by MrHomebrew** [corpnewt/Lilu-and-Friends#38]
I have noticed that when trying to compile voodooi2c the build fails. Any chance this can be looked in to?

**Comment by corpnewt** [comment]
VoodooI2C has been notoriously difficult to get compiling in my experience.  I know I had fixed it some time ago (by stripping build phases directly out of the project) - but I can give it another look if I have time.

-CorpNewt

**Comment by corpnewt** [comment]
Should be fixed with [this commit](https://github.com/corpnewt/Lilu-and-Friends/commit/b0927782bbce5ee261226be721c984cc28d1984f).

-CorpNewt
