### ISSUE TITLE
IntelBluetoothFirmware won't compile

### ISSUE THREAD

**Issue by mhschaap** [corpnewt/Lilu-and-Friends#42]
Hello! Many thanks for the great tool! I am very new to compiling under MacOS, so please ignore if this question is too obvious. I have successfully built seven kexts, but the eigth is failing: IntelBluetoothFirmware. Please find the Terminal output in this screenshot. I hope this info is helpful.

<img width="570" alt="Scherm­afbeelding 2022-12-11 om 18 53 43" src="https://user-images.githubusercontent.com/50181427/206920276-580f4839-3de5-49f2-b106-eb6db94e106d.png">

**Comment by corpnewt** [comment]
Hey there - what macOS and Xcode versions are you running currently?  I can test locally and see if I run into the same issue.

-CorpNewt

**Comment by mhschaap** [comment]
Thanks for asking: MacOS 13.0.1 (build 22A400) - Xcode 14.1 (14B47b)

**Comment by corpnewt** [comment]
I just tried building on 13.1 b4 with Xcode 14.0 and it also failed.  I'll test on Monterey with an older Xcode version and see if it compiles there - if so, the developer may need to update their code for Xcode 14.x.

-CorpNewt

**Comment by mhschaap** [comment]
> I just tried building on 13.1 b4 with Xcode 14.0 and it also failed. 

Thank you for testing! Should I inform the developer?

**Comment by corpnewt** [comment]
Let me verify that it compiles on an older Xcode version first. I'll update here when I've had a chance to test.

-CorpNewt

**Comment by mhschaap** [comment]
Hi! Just FYI: my run with MacOS 13.1 (22C65) and Xcode 14.2 (14C18) results in the same issue as above with 13.0.1 and Xcode 14.1

**Comment by corpnewt** [comment]
Builds fine on Monterey 12.6.2 (21G320) running Xcode 13.2.1 - so I'm guessing it's either an Xcode 14.x or macOS 13.x issue at this point:

![image](https://user-images.githubusercontent.com/12772521/207956846-a23b7a2e-cc8f-4a84-976d-d3ea9a61df6e.png)

-CorpNewt

**Comment by mhschaap** [comment]
Many thanks, CorpNewt! Credits are for you! Will you be able to report it, or do you want me to pass it on?

**Comment by corpnewt** [comment]
You are welcome to if you'd like.  I only use IntelBluetoothFirmware on Monterey currently, so I won't be terribly useful if they request Ventura testing.

-CorpNewt

**Comment by mhschaap** [comment]
Alright, I will pass it on! The pre-compiled kext works fine for me. But it won't hurt if they are aware of the issue.

**Comment by pigworlds** [comment]
It seems to be a bug in the plugins.json file. I don't know why it works on Monterey.

See the fix here https://github.com/corpnewt/Lilu-and-Friends/compare/master...pigworlds:Lilu-and-Friends:fixibf

**Comment by corpnewt** [comment]
I'll give it a look and see if it compiles locally, thank you!

-CorpNewt

**Comment by corpnewt** [comment]
Yep - worked here, pushed the change to the main repo.  Thanks for that @pigworlds 

-CorpNewt

**Comment by corpnewt** [comment]
Just leaving this here as well - it still builds fine on Monterey with Xcode 13 as well:

![image](https://user-images.githubusercontent.com/12772521/208008406-6e42a306-81e7-4469-9cfe-d23009319245.png)
