### ISSUE TITLE
Small Request

### ISSUE THREAD

**Issue by webfalter** [corpnewt/Lilu-and-Friends#5]
Hello,
can you please https://github.com/alexandred/VoodooI2C in your script

best regards

**Comment by corpnewt** [comment]
I added it with version 0.0.24.  It looks like they require some extra py2 libraries to generate the documentation, and I struggled to get those installed correctly on my system - so the kext will actually build with a warning if those fail (I added an Ignore Errors flag to the json entry).  Please let me know if they work for you or not and I'll do more digging if need be.

**Comment by webfalter** [comment]
```
  #######################################################
 #                 0 of 1 Succeeded                    #
#######################################################
Succeeded:
    None
Failed:
    VoodooI2C
Build took 12 seconds.
Press [enter] to return to the main menu...
```
Thank you for making the effort. Unfortunately, the kext is not created.

**Comment by corpnewt** [comment]
If you scroll up in the script it will give you some more output on why it failed. Could you send that here too and I'll see if I can help you figure it out!

**Comment by webfalter** [comment]
```
  #######################################################
 #                  Building 1 kext                    #
#######################################################
Building VoodooI2C (1 of 1)
    Downloading VoodooI2C...
    Building release version...
    Build had errors - attempting to continue past the following:
** BUILD FAILED **
The following build commands failed:
	PhaseScriptExecution Generate\ Documentation /Users/xxx/Library/Developer/Xcode/DerivedData/VoodooI2C-fqhaybtyeuvzswdijhxlubavkwin/Build/Intermediates.noindex/VoodooI2C.build/Release/VoodooI2C.build/Script-AC4EEE2D1F3B2F1D00D0A6E0.sh
(1 failure)

[Errno 2] No such file or directory: './build/Products/Release'
An error occurred!
Cleaning up...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

**Comment by corpnewt** [comment]
You'll likely want to install the dependencies for that kext to build. Those were the issues I ran into as well. There's a c++ linter and a document generator module that are listed in the [circle.yml](https://github.com/alexandred/VoodooI2C/blob/master/circle.yml). Outside that, I'm not sure what to tell you.

**Comment by webfalter** [comment]
Thank you for your help
How does WhateverGreen get involved as a Lilu plugin?
https://github.com/vit9696/WhateverGreen
I would like to get involved

**Comment by corpnewt** [comment]
WhateverGreen is currently closed-source so the actual source code is not publicly available. You could message vit9696 if you'd like to get involved in development, but other than that, you'll just have to rely on the public releases.
