### ISSUE TITLE
Whatevergreen

### ISSUE THREAD

**Issue by XiaopanOS** [corpnewt/Lilu-and-Friends#7]
Great little app I must say. Can we get whatevergreen to the list?

Model detection code is open https://github.com/vit9696/WhateverGreen/blob/master/WhateverGreen/kern_model.cpp

**Comment by corpnewt** [comment]
I'll look into building it tonight and see what happens.  If all goes well, I'll add it for sure.

**Comment by corpnewt** [comment]
Tested and it builds - I don't have an AMD GPU to verify against - but it's added.
