### ISSUE TITLE
Building VoodooI2C Fails.

### ISSUE THREAD

**Issue by ReddestDream** [corpnewt/Lilu-and-Friends#8]
```
Building VoodooI2C (12 of 12)
    Downloading VoodooI2C...
    Building release version...
[Errno 2] No such file or directory: './build/Products/Release'
An error occurred!
Cleaning up...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

And I am sad. :(

macOS 10.13.3. Xcode 9.2

**Comment by corpnewt** [comment]
Yeah, currently it's a bit of a struggle to build.  I know they list extra dependencies in their [circle.yml](https://github.com/alexandred/VoodooI2C/blob/master/circle.yml) - which may be of some use.  I also have the kext set to ignore errors when building in the *plugins.json*.  This does suppress some of the errors though as it just tries to work past it - you may get more output by changing `"Ignore Errors": true,` to `"Ignore Errors": false,` in the following:

    {
      "Build Opts": [
        "-workspace", 
        "VoodooI2C.xcworkspace", 
        "-scheme", 
        "VoodooI2C", 
        "-sdk", 
        "macosx", 
        "DEBUG_INFORMATION_FORMAT=none"
      ], 
      "Build Dir": "./build/Products/Release", 
      "Name": "VoodooI2C", 
      "Zip": "../Release", 
      "URL": "git clone --recursive -j8 https://github.com/alexandred/VoodooI2C", 
      "Ignore Errors": true, 
      "Desc": "Intel Lynxpoint I2C controller and device driver for OS X"
    },

**Comment by corpnewt** [comment]
al3xtjames gave me some insight on the build phases causing the issue - so I wrote a routine to remove specified phases.  VoodooI2C should now actually build.
